/** @type {import('tailwindcss').Config} */

export default {
  content: [
    './index.html',
    './src/**/*.{vue,ts,js,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // All MD3 tokens wired to CSS custom properties for automatic dark-mode switching.
        // Values are RGB triplets; the <alpha-value> placeholder enables Tailwind opacity modifiers.
        background:                'rgb(var(--color-background) / <alpha-value>)',
        'on-background':           'rgb(var(--color-on-background) / <alpha-value>)',
        surface:                   'rgb(var(--color-surface) / <alpha-value>)',
        'on-surface':              'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant':      'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'surface-container-lowest':'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low':   'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container':       'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high':  'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest':'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'surface-dim':             'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright':          'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-variant':         '#e0e3e5',
        'outline-variant':         'rgb(var(--color-outline-variant) / <alpha-value>)',
        outline:                   'rgb(var(--color-outline) / <alpha-value>)',
        'inverse-surface':         'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':      'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        primary:                   'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary':              'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container':       'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container':    'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'inverse-primary':         'rgb(var(--color-inverse-primary) / <alpha-value>)',
        'primary-fixed':           'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim':       'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed':        '#0f0069',
        'on-primary-fixed-variant':'#3323cc',
        secondary:                 'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary':            '#ffffff',
        'secondary-container':     'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container':  'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        'secondary-fixed':         '#dae2fd',
        'secondary-fixed-dim':     '#bec6e0',
        'on-secondary-fixed':      '#131b2e',
        'on-secondary-fixed-variant':'#3f465c',
        error:                     'rgb(var(--color-error) / <alpha-value>)',
        'on-error':                'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container':         'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container':      'rgb(var(--color-on-error-container) / <alpha-value>)',
        tertiary:                  'rgb(var(--color-tertiary) / <alpha-value>)',
        'on-tertiary':             '#ffffff',
        'tertiary-container':      'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-tertiary-container':   'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
        'tertiary-fixed':          '#e1e0ff',
        'tertiary-fixed-dim':      '#c0c1ff',
        'on-tertiary-fixed':       '#07006c',
        'on-tertiary-fixed-variant':'#2f2ebe',
        'surface-tint':            'rgb(var(--color-surface-tint) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'sidebar-collapsed': '64px',
        gutter: '16px',
        base: '4px',
        'stack-md': '16px',
        'container-padding': '24px',
        'sidebar-width': '260px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'code-md': ['13px', { lineHeight: '20px', fontWeight: '450' }],
      },
    },
  },
  plugins: [],
}
