/** @type {import('tailwindcss').Config} */

export default {
  content: [
    './index.html',
    './src/**/*.{vue,ts,js,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // MD3 color tokens
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-tertiary-container': '#d9d8ff',
        'on-surface-variant': '#464555',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-container': '#5c647a',
        surface: '#f7f9fb',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#bec6e0',
        secondary: '#565e74',
        'on-surface': '#191c1e',
        'on-primary-container': '#dad7ff',
        'tertiary-fixed': '#e1e0ff',
        'tertiary-container': '#4b4dd8',
        'surface-tint': '#4d44e3',
        'surface-container': '#eceef0',
        'on-primary': '#ffffff',
        'secondary-fixed': '#dae2fd',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'outline-variant': '#c7c4d8',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-fixed': '#07006c',
        primary: '#3525cd',
        'tertiary-fixed-dim': '#c0c1ff',
        'error-container': '#ffdad6',
        'surface-bright': '#f7f9fb',
        'primary-container': '#4f46e5',
        'on-primary-fixed-variant': '#3323cc',
        'on-background': '#191c1e',
        outline: '#777587',
        tertiary: '#3130c0',
        'surface-dim': '#d8dadc',
        'on-primary-fixed': '#0f0069',
        'inverse-surface': '#2d3133',
        background: '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'on-secondary-fixed-variant': '#3f465c',
        'on-error': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'secondary-container': '#dae2fd',
        'inverse-primary': '#c3c0ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'sidebar-collapsed': '64px',
        gutter: '16px',
        base: '4px',
        'stack-md': '16px',
        'container-padding': '24px',
        'sidebar-width': '260px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'code-md': ['13px', { lineHeight: '20px', fontWeight: '450' }],
      },
    },
  },
  plugins: [],
}
